const quoteLinesArray = [
  {
    extreme_quoteLineId: 'd1e8f8b6-4c3a-4f8b-8e8f-8b6d4c3a4f8b',
    extreme_productNumber: 1,
    extreme_productName: 'HP-Laptop',
    extreme_productSinglePrice: 1200.00,
    extreme_productCurrency: 'USD',
    extreme_productQuantity: 10,
    extreme_productTotalPrice: 12000.00,
    extreme_productThermoDiscount: 5,
    extreme_productMargin: 15,
    extreme_productSaleSignlePrice: 1140.00,
    extreme_productSaleTotalPrice: 11400.00,
    extreme_productFinalDiscount: 10,
    extreme_productSaleTotalPriceWithDiscount: 10260.00,
    extreme_productBaseSaleTotalPriceDifference: 1740.00,
    extreme_productPriceList: 'Standard'
  },
  {
    extreme_quoteLineId: 'e2f9g9c7-5d4b-5g9c-9f9g-9c7e5d4b5g9c',
    extreme_productNumber: 2,
    extreme_productName: 'Dell-Laptop',
    extreme_productSinglePrice: 1100.00,
    extreme_productCurrency: 'USD',
    extreme_productQuantity: 8,
    extreme_productTotalPrice: 8800.00,
    extreme_productThermoDiscount: 4,
    extreme_productMargin: 12,
    extreme_productSaleSignlePrice: 1056.00,
    extreme_productSaleTotalPrice: 8448.00,
    extreme_productFinalDiscount: 8,
    extreme_productSaleTotalPriceWithDiscount: 7771.20,
    extreme_productBaseSaleTotalPriceDifference: 1028.80,
    extreme_productPriceList: 'Premium'
  },
  {
    extreme_quoteLineId: 'f3g0h0d8-6e5c-6h0d-0g0h-0d8f6e5c6h0d',
    extreme_productNumber: 3,
    extreme_productName: 'Lenovo-Laptop',
    extreme_productSinglePrice: 950.00,
    extreme_productCurrency: 'USD',
    extreme_productQuantity: 15,
    extreme_productTotalPrice: 14250.00,
    extreme_productThermoDiscount: 6,
    extreme_productMargin: 10,
    extreme_productSaleSignlePrice: 893.00,
    extreme_productSaleTotalPrice: 13395.00,
    extreme_productFinalDiscount: 7,
    extreme_productSaleTotalPriceWithDiscount: 12457.35,
    extreme_productBaseSaleTotalPriceDifference: 1792.65,
    extreme_productPriceList: 'Economy'
  },
  {
    extreme_quoteLineId: 'g4h1i1e9-7f6d-7i1e-1h1i-1e9g7f6d7i1e',
    extreme_productNumber: 4,
    extreme_productName: 'Acer-Laptop',
    extreme_productSinglePrice: 800.00,
    extreme_productCurrency: 'USD',
    extreme_productQuantity: 12,
    extreme_productTotalPrice: 9600.00,
    extreme_productThermoDiscount: 3,
    extreme_productMargin: 8,
    extreme_productSaleSignlePrice: 776.00,
    extreme_productSaleTotalPrice: 9312.00,
    extreme_productFinalDiscount: 5,
    extreme_productSaleTotalPriceWithDiscount: 8846.40,
    extreme_productBaseSaleTotalPriceDifference: 753.60,
    extreme_productPriceList: 'Standard'
  },
  {
    extreme_quoteLineId: 'h5i2j2f0-8g7e-8j2f-2i2j-2f0h8g7e8j2f',
    extreme_productNumber: 5,
    extreme_productName: 'Asus-Laptop',
    extreme_productSinglePrice: 1050.00,
    extreme_productCurrency: 'USD',
    extreme_productQuantity: 9,
    extreme_productTotalPrice: 9450.00,
    extreme_productThermoDiscount: 4,
    extreme_productMargin: 11,
    extreme_productSaleSignlePrice: 1008.00,
    extreme_productSaleTotalPrice: 9072.00,
    extreme_productFinalDiscount: 6,
    extreme_productSaleTotalPriceWithDiscount: 8527.68,
    extreme_productBaseSaleTotalPriceDifference: 922.32,
    extreme_productPriceList: 'Premium'
  },
  {
    extreme_quoteLineId: 'i6j3k3g1-9h8f-9k3g-3j3k-3g1i9h8f9k3g',
    extreme_productNumber: 6,
    extreme_productName: 'Apple-MacBook',
    extreme_productSinglePrice: 1500.00,
    extreme_productCurrency: 'USD',
    extreme_productQuantity: 5,
    extreme_productTotalPrice: 7500.00,
    extreme_productThermoDiscount: 7,
    extreme_productMargin: 20,
    extreme_productSaleSignlePrice: 1395.00,
    extreme_productSaleTotalPrice: 6975.00,
    extreme_productFinalDiscount: 10,
    extreme_productSaleTotalPriceWithDiscount: 6277.50,
    extreme_productBaseSaleTotalPriceDifference: 1222.50,
    extreme_productPriceList: 'Luxury'
  },
  {
    extreme_quoteLineId: 'j7k4l4h2-0i9g-0l4h-4k4l-4h2j0i9g0l4h',
    extreme_productNumber: 7,
    extreme_productName: 'Microsoft-Surface',
    extreme_productSinglePrice: 1300.00,
    extreme_productCurrency: 'USD',
    extreme_productQuantity: 7,
    extreme_productTotalPrice: 9100.00,
    extreme_productThermoDiscount: 5,
    extreme_productMargin: 18,
    extreme_productSaleSignlePrice: 1235.00,
    extreme_productSaleTotalPrice: 8645.00,
    extreme_productFinalDiscount: 9,
    extreme_productSaleTotalPriceWithDiscount: 7866.95,
    extreme_productBaseSaleTotalPriceDifference: 1233.05,
    extreme_productPriceList: 'Standard'
  },
  {
    extreme_quoteLineId: 'k8l5m5i3-1j0h-1m5i-5l5m-5i3k1j0h1m5i',
    extreme_productNumber: 8,
    extreme_productName: 'Samsung-Laptop',
    extreme_productSinglePrice: 900.00,
    extreme_productCurrency: 'USD',
    extreme_productQuantity: 10,
    extreme_productTotalPrice: 9000.00,
    extreme_productThermoDiscount: 4,
    extreme_productMargin: 10,
    extreme_productSaleSignlePrice: 864.00,
    extreme_productSaleTotalPrice: 8640.00,
    extreme_productFinalDiscount: 6,
    extreme_productSaleTotalPriceWithDiscount: 8121.60,
    extreme_productBaseSaleTotalPriceDifference: 878.40,
    extreme_productPriceList: 'Economy'
  },
  {
    extreme_quoteLineId: 'l9m6n6j4-2k1i-2n6j-6m6n-6j4l2k1i2n6j',
    extreme_productNumber: 9,
    extreme_productName: 'Toshiba-Laptop',
    extreme_productSinglePrice: 850.00,
    extreme_productCurrency: 'USD',
    extreme_productQuantity: 8,
    extreme_productTotalPrice: 6800.00,
    extreme_productThermoDiscount: 3,
    extreme_productMargin: 9,
    extreme_productSaleSignlePrice: 824.50,
    extreme_productSaleTotalPrice: 6596.00,
    extreme_productFinalDiscount: 5,
    extreme_productSaleTotalPriceWithDiscount: 6266.20,
    extreme_productBaseSaleTotalPriceDifference: 533.80,
    extreme_productPriceList: 'Standard'
  },
  {
    extreme_quoteLineId: 'm0n7o7k5-3l2j-3o7k-7n7o-7k5m3l2j3o7k',
    extreme_productNumber: 10,
    extreme_productName: 'Sony-Laptop',
    extreme_productSinglePrice: 1000.00,
    extreme_productCurrency: 'USD',
    extreme_productQuantity: 6,
    extreme_productTotalPrice: 6000.00,
    extreme_productThermoDiscount: 5,
    extreme_productMargin: 12,
    extreme_productSaleSignlePrice: 950.00,
    extreme_productSaleTotalPrice: 5700.00,
    extreme_productFinalDiscount: 7,
    extreme_productSaleTotalPriceWithDiscount: 5301.00,
    extreme_productBaseSaleTotalPriceDifference: 699.00,
    extreme_productPriceList: 'Premium'
  }
];


const inventoryExample = [
  {
    inventory_name: 'HP-Laptop',
    inventory_quantity: 100,
  },
  {
    inventory_name: 'Dell-Laptop',
    inventory_quantity: 200,
  },
  {
    inventory_name: 'Lenovo-Laptop',
    inventory_quantity: 150,
  },
  {
    inventory_name: 'Acer-Laptop',
    inventory_quantity: 300,
  },
  {
    inventory_name: 'Asus-Laptop',
    inventory_quantity: 250,
  }
]