const quoteLinesArray = [
  {
    extreme_quoteLineId: 'd1e8f8b6-4c3a-4f8b-8e8f-8b6d4c3a4f8b',
    extreme_productNumber: 1,
    extreme_productName: 'HP-Laptop',
    extreme_productSinglePrice: 1200.00,
    extreme_productCurrency: 'USD',
    extreme_productQuantity: 10,
    extreme_productTotalPrice: 12000.00,
    extreme_productThermoDiscount: 5,
    extreme_productMargin: 15,
    extreme_productSaleSignlePrice: 1140.00,
    extreme_productSaleTotalPrice: 11400.00,
    extreme_productFinalDiscount: 10,
    extreme_productSaleTotalPriceWithDiscount: 10260.00,
    extreme_productBaseSaleTotalPriceDifference: 1740.00,
    extreme_productPriceList: 'Standard'
  },
  {
    extreme_quoteLineId: 'e2f9g9c7-5d4b-5g9c-9f9g-9c7e5d4b5g9c',
    extreme_productNumber: 2,
    extreme_productName: 'Dell-Laptop',
    extreme_productSinglePrice: 1100.00,
    extreme_productCurrency: 'USD',
    extreme_productQuantity: 8,
    extreme_productTotalPrice: 8800.00,
    extreme_productThermoDiscount: 4,
    extreme_productMargin: 12,
    extreme_productSaleSignlePrice: 1056.00,
    extreme_productSaleTotalPrice: 8448.00,
    extreme_productFinalDiscount: 8,
    extreme_productSaleTotalPriceWithDiscount: 7771.20,
    extreme_productBaseSaleTotalPriceDifference: 1028.80,
    extreme_productPriceList: 'Premium'
  },
  {
    extreme_quoteLineId: 'f3g0h0d8-6e5c-6h0d-0g0h-0d8f6e5c6h0d',
    extreme_productNumber: 3,
    extreme_productName: 'Lenovo-Laptop',
    extreme_productSinglePrice: 950.00,
    extreme_productCurrency: 'USD',
    extreme_productQuantity: 15,
    extreme_productTotalPrice: 14250.00,
    extreme_productThermoDiscount: 6,
    extreme_productMargin: 10,
    extreme_productSaleSignlePrice: 893.00,
    extreme_productSaleTotalPrice: 13395.00,
    extreme_productFinalDiscount: 7,
    extreme_productSaleTotalPriceWithDiscount: 12457.35,
    extreme_productBaseSaleTotalPriceDifference: 1792.65,
    extreme_productPriceList: 'Economy'
  },
  {
    extreme_quoteLineId: 'g4h1i1e9-7f6d-7i1e-1h1i-1e9g7f6d7i1e',
    extreme_productNumber: 4,
    extreme_productName: 'Acer-Laptop',
    extreme_productSinglePrice: 800.00,
    extreme_productCurrency: 'USD',
    extreme_productQuantity: 12,
    extreme_productTotalPrice: 9600.00,
    extreme_productThermoDiscount: 3,
    extreme_productMargin: 8,
    extreme_productSaleSignlePrice: 776.00,
    extreme_productSaleTotalPrice: 9312.00,
    extreme_productFinalDiscount: 5,
    extreme_productSaleTotalPriceWithDiscount: 8846.40,
    extreme_productBaseSaleTotalPriceDifference: 753.60,
    extreme_productPriceList: 'Standard'
  },
  {
    extreme_quoteLineId: 'h5i2j2f0-8g7e-8j2f-2i2j-2f0h8g7e8j2f',
    extreme_productNumber: 5,
    extreme_productName: 'Asus-Laptop',
    extreme_productSinglePrice: 1050.00,
    extreme_productCurrency: 'USD',
    extreme_productQuantity: 9,
    extreme_productTotalPrice: 9450.00,
    extreme_productThermoDiscount: 4,
    extreme_productMargin: 11,
    extreme_productSaleSignlePrice: 1008.00,
    extreme_productSaleTotalPrice: 9072.00,
    extreme_productFinalDiscount: 6,
    extreme_productSaleTotalPriceWithDiscount: 8527.68,
    extreme_productBaseSaleTotalPriceDifference: 922.32,
    extreme_productPriceList: 'Premium'
  },
  {
    extreme_quoteLineId: 'i6j3k3g1-9h8f-9k3g-3j3k-3g1i9h8f9k3g',
    extreme_productNumber: 6,
    extreme_productName: 'Apple-MacBook',
    extreme_productSinglePrice: 1500.00,
    extreme_productCurrency: 'USD',
    extreme_productQuantity: 5,
    extreme_productTotalPrice: 7500.00,
    extreme_productThermoDiscount: 7,
    extreme_productMargin: 20,
    extreme_productSaleSignlePrice: 1395.00,
    extreme_productSaleTotalPrice: 6975.00,
    extreme_productFinalDiscount: 10,
    extreme_productSaleTotalPriceWithDiscount: 6277.50,
    extreme_productBaseSaleTotalPriceDifference: 1222.50,
    extreme_productPriceList: 'Luxury'
  },
  {
    extreme_quoteLineId: 'j7k4l4h2-0i9g-0l4h-4k4l-4h2j0i9g0l4h',
    extreme_productNumber: 7,
    extreme_productName: 'Microsoft-Surface',
    extreme_productSinglePrice: 1300.00,
    extreme_productCurrency: 'USD',
    extreme_productQuantity: 7,
    extreme_productTotalPrice: 9100.00,
    extreme_productThermoDiscount: 5,
    extreme_productMargin: 18,
    extreme_productSaleSignlePrice: 1235.00,
    extreme_productSaleTotalPrice: 8645.00,
    extreme_productFinalDiscount: 9,
    extreme_productSaleTotalPriceWithDiscount: 7866.95,
    extreme_productBaseSaleTotalPriceDifference: 1233.05,
    extreme_productPriceList: 'Standard'
  },
  {
    extreme_quoteLineId: 'k8l5m5i3-1j0h-1m5i-5l5m-5i3k1j0h1m5i',
    extreme_productNumber: 8,
    extreme_productName: 'Samsung-Laptop',
    extreme_productSinglePrice: 900.00,
    extreme_productCurrency: 'USD',
    extreme_productQuantity: 10,
    extreme_productTotalPrice: 9000.00,
    extreme_productThermoDiscount: 4,
    extreme_productMargin: 10,
    extreme_productSaleSignlePrice: 864.00,
    extreme_productSaleTotalPrice: 8640.00,
    extreme_productFinalDiscount: 6,
    extreme_productSaleTotalPriceWithDiscount: 8121.60,
    extreme_productBaseSaleTotalPriceDifference: 878.40,
    extreme_productPriceList: 'Economy'
  },
  {
    extreme_quoteLineId: 'l9m6n6j4-2k1i-2n6j-6m6n-6j4l2k1i2n6j',
    extreme_productNumber: 9,
    extreme_productName: 'Toshiba-Laptop',
    extreme_productSinglePrice: 850.00,
    extreme_productCurrency: 'USD',
    extreme_productQuantity: 8,
    extreme_productTotalPrice: 6800.00,
    extreme_productThermoDiscount: 3,
    extreme_productMargin: 9,
    extreme_productSaleSignlePrice: 824.50,
    extreme_productSaleTotalPrice: 6596.00,
    extreme_productFinalDiscount: 5,
    extreme_productSaleTotalPriceWithDiscount: 6266.20,
    extreme_productBaseSaleTotalPriceDifference: 533.80,
    extreme_productPriceList: 'Standard'
  },
  {
    extreme_quoteLineId: 'm0n7o7k5-3l2j-3o7k-7n7o-7k5m3l2j3o7k',
    extreme_productNumber: 10,
    extreme_productName: 'Sony-Laptop',
    extreme_productSinglePrice: 1000.00,
    extreme_productCurrency: 'USD',
    extreme_productQuantity: 6,
    extreme_productTotalPrice: 6000.00,
    extreme_productThermoDiscount: 5,
    extreme_productMargin: 12,
    extreme_productSaleSignlePrice: 950.00,
    extreme_productSaleTotalPrice: 5700.00,
    extreme_productFinalDiscount: 7,
    extreme_productSaleTotalPriceWithDiscount: 5301.00,
    extreme_productBaseSaleTotalPriceDifference: 699.00,
    extreme_productPriceList: 'Premium'
  }
];


const inventoryExample = [
  {
    inventory_name: 'HP-Laptop',
    inventory_quantity: 100,
  },
  {
    inventory_name: 'Dell-Laptop',
    inventory_quantity: 200,
  },
  {
    inventory_name: 'Lenovo-Laptop',
    inventory_quantity: 150,
  },
  {
    inventory_name: 'Acer-Laptop',
    inventory_quantity: 300,
  },
  {
    inventory_name: 'Asus-Laptop',
    inventory_quantity: 250,
  }
]


const employees = [{
  ID: 1,
  Head_ID: -1,
  Full_Name: 'John Heart',
  Prefix: 'Mr.',
  Title: 'CEO',
  City: 'Los Angeles',
  State: 'California',
  Email: 'jheart@dx-email.com',
  Skype: 'jheart_DX_skype',
  Mobile_Phone: '(213) 555-9392',
  Birth_Date: '1964-03-16',
  Hire_Date: '1995-01-15',
}, {
  ID: 2,
  Head_ID: 1,
  Full_Name: 'Samantha Bright',
  Prefix: 'Dr.',
  Title: 'COO',
  City: 'Los Angeles',
  State: 'California',
  Email: 'samanthab@dx-email.com',
  Skype: 'samanthab_DX_skype',
  Mobile_Phone: '(213) 555-2858',
  Birth_Date: '1966-05-02',
  Hire_Date: '2004-05-24',
}, {
  ID: 3,
  Head_ID: 1,
  Full_Name: 'Arthur Miller',
  Prefix: 'Mr.',
  Title: 'CTO',
  City: 'Denver',
  State: 'Colorado',
  Email: 'arthurm@dx-email.com',
  Skype: 'arthurm_DX_skype',
  Mobile_Phone: '(310) 555-8583',
  Birth_Date: '1972-07-11',
  Hire_Date: '2007-12-18',
}, {
  ID: 4,
  Head_ID: 1,
  Full_Name: 'Robert Reagan',
  Prefix: 'Mr.',
  Title: 'CMO',
  City: 'Bentonville',
  State: 'Arkansas',
  Email: 'robertr@dx-email.com',
  Skype: 'robertr_DX_skype',
  Mobile_Phone: '(818) 555-2387',
  Birth_Date: '1974-09-07',
  Hire_Date: '2002-11-08',
}, {
  ID: 5,
  Head_ID: 1,
  Full_Name: 'Greta Sims',
  Prefix: 'Ms.',
  Title: 'HR Manager',
  City: 'Atlanta',
  State: 'Georgia',
  Email: 'gretas@dx-email.com',
  Skype: 'gretas_DX_skype',
  Mobile_Phone: '(818) 555-6546',
  Birth_Date: '1977-11-22',
  Hire_Date: '1998-04-23',
}, {
  ID: 6,
  Head_ID: 3,
  Full_Name: 'Brett Wade',
  Prefix: 'Mr.',
  Title: 'IT Manager',
  City: 'Reno',
  State: 'Nevada',
  Email: 'brettw@dx-email.com',
  Skype: 'brettw_DX_skype',
  Mobile_Phone: '(626) 555-0358',
  Birth_Date: '1968-12-01',
  Hire_Date: '2009-03-06',
}, {
  ID: 7,
  Head_ID: 5,
  Full_Name: 'Sandra Johnson',
  Prefix: 'Mrs.',
  Title: 'Controller',
  City: 'Beaver',
  State: 'Utah',
  Email: 'sandraj@dx-email.com',
  Skype: 'sandraj_DX_skype',
  Mobile_Phone: '(562) 555-2082',
  Birth_Date: '1974-11-15',
  Hire_Date: '2005-05-11',
}, {
  ID: 8,
  Head_ID: 4,
  Full_Name: 'Ed Holmes',
  Prefix: 'Dr.',
  Title: 'Sales Manager',
  City: 'Malibu',
  State: 'California',
  Email: 'edwardh@dx-email.com',
  Skype: 'edwardh_DX_skype',
  Mobile_Phone: '(310) 555-1288',
  Birth_Date: '1973-07-14',
  Hire_Date: '2005-06-19',
}, {
  ID: 9,
  Head_ID: 3,
  Full_Name: 'Barb Banks',
  Prefix: 'Mrs.',
  Title: 'Support Manager',
  City: 'Phoenix',
  State: 'Arizona',
  Email: 'barbarab@dx-email.com',
  Skype: 'barbarab_DX_skype',
  Mobile_Phone: '(310) 555-3355',
  Birth_Date: '1979-04-14',
  Hire_Date: '2002-08-07',
}, {
  ID: 10,
  Head_ID: 2,
  Full_Name: 'Kevin Carter',
  Prefix: 'Mr.',
  Title: 'Shipping Manager',
  City: 'San Diego',
  State: 'California',
  Email: 'kevinc@dx-email.com',
  Skype: 'kevinc_DX_skype',
  Mobile_Phone: '(213) 555-2840',
  Birth_Date: '1978-01-09',
  Hire_Date: '2009-08-11',
}, {
  ID: 11,
  Head_ID: 5,
  Full_Name: 'Cindy Stanwick',
  Prefix: 'Ms.',
  Title: 'HR Assistant',
  City: 'Little Rock',
  State: 'Arkansas',
  Email: 'cindys@dx-email.com',
  Skype: 'cindys_DX_skype',
  Mobile_Phone: '(818) 555-6655',
  Birth_Date: '1985-06-05',
  Hire_Date: '2008-03-24',
}, {
  ID: 12,
  Head_ID: 8,
  Full_Name: 'Sammy Hill',
  Prefix: 'Mr.',
  Title: 'Sales Assistant',
  City: 'Pasadena',
  State: 'California',
  Email: 'sammyh@dx-email.com',
  Skype: 'sammyh_DX_skype',
  Mobile_Phone: '(626) 555-7292',
  Birth_Date: '1984-02-17',
  Hire_Date: '2012-02-01',
}, {
  ID: 13,
  Head_ID: 10,
  Full_Name: 'Davey Jones',
  Prefix: 'Mr.',
  Title: 'Shipping Assistant',
  City: 'Pasadena',
  State: 'California',
  Email: 'davidj@dx-email.com',
  Skype: 'davidj_DX_skype',
  Mobile_Phone: '(626) 555-0281',
  Birth_Date: '1983-03-06',
  Hire_Date: '2011-04-24',
}, {
  ID: 14,
  Head_ID: 10,
  Full_Name: 'Victor Norris',
  Prefix: 'Mr.',
  Title: 'Shipping Assistant',
  City: 'Little Rock',
  State: 'Arkansas',
  Email: 'victorn@dx-email.com',
  Skype: 'victorn_DX_skype',
  Mobile_Phone: '(213) 555-9278',
  Birth_Date: '1986-07-23',
  Hire_Date: '2012-07-23',
}, {
  ID: 15,
  Head_ID: 10,
  Full_Name: 'Mary Stern',
  Prefix: 'Ms.',
  Title: 'Shipping Assistant',
  City: 'Beaver',
  State: 'Utah',
  Email: 'marys@dx-email.com',
  Skype: 'marys_DX_skype',
  Mobile_Phone: '(818) 555-7857',
  Birth_Date: '1982-04-08',
  Hire_Date: '2012-08-12',
}, {
  ID: 16,
  Head_ID: 10,
  Full_Name: 'Robin Cosworth',
  Prefix: 'Mrs.',
  Title: 'Shipping Assistant',
  City: 'Los Angeles',
  State: 'California',
  Email: 'robinc@dx-email.com',
  Skype: 'robinc_DX_skype',
  Mobile_Phone: '(818) 555-0942',
  Birth_Date: '1981-06-12',
  Hire_Date: '2012-09-01',
}, {
  ID: 17,
  Head_ID: 9,
  Full_Name: 'Kelly Rodriguez',
  Prefix: 'Ms.',
  Title: 'Support Assistant',
  City: 'Boise',
  State: 'Idaho',
  Email: 'kellyr@dx-email.com',
  Skype: 'kellyr_DX_skype',
  Mobile_Phone: '(818) 555-9248',
  Birth_Date: '1988-05-11',
  Hire_Date: '2012-10-13',
}, {
  ID: 18,
  Head_ID: 9,
  Full_Name: 'James Anderson',
  Prefix: 'Mr.',
  Title: 'Support Assistant',
  City: 'Atlanta',
  State: 'Georgia',
  Email: 'jamesa@dx-email.com',
  Skype: 'jamesa_DX_skype',
  Mobile_Phone: '(323) 555-4702',
  Birth_Date: '1987-01-29',
  Hire_Date: '2012-10-18',
}, {
  ID: 19,
  Head_ID: 9,
  Full_Name: 'Antony Remmen',
  Prefix: 'Mr.',
  Title: 'Support Assistant',
  City: 'Boise',
  State: 'Idaho',
  Email: 'anthonyr@dx-email.com',
  Skype: 'anthonyr_DX_skype',
  Mobile_Phone: '(310) 555-6625',
  Birth_Date: '1986-02-19',
  Hire_Date: '2013-01-19',
}, {
  ID: 20,
  Head_ID: 8,
  Full_Name: 'Olivia Peyton',
  Prefix: 'Mrs.',
  Title: 'Sales Assistant',
  City: 'Atlanta',
  State: 'Georgia',
  Email: 'oliviap@dx-email.com',
  Skype: 'oliviap_DX_skype',
  Mobile_Phone: '(310) 555-2728',
  Birth_Date: '1981-06-03',
  Hire_Date: '2012-05-14',
}, {
  ID: 21,
  Head_ID: 6,
  Full_Name: 'Taylor Riley',
  Prefix: 'Mr.',
  Title: 'Network Admin',
  City: 'San Jose',
  State: 'California',
  Email: 'taylorr@dx-email.com',
  Skype: 'taylorr_DX_skype',
  Mobile_Phone: '(310) 555-7276',
  Birth_Date: '1982-08-14',
  Hire_Date: '2012-04-14',
}, {
  ID: 22,
  Head_ID: 6,
  Full_Name: 'Amelia Harper',
  Prefix: 'Mrs.',
  Title: 'Network Admin',
  City: 'Los Angeles',
  State: 'California',
  Email: 'ameliah@dx-email.com',
  Skype: 'ameliah_DX_skype',
  Mobile_Phone: '(213) 555-4276',
  Birth_Date: '1983-11-19',
  Hire_Date: '2011-02-10',
}, {
  ID: 23,
  Head_ID: 6,
  Full_Name: 'Wally Hobbs',
  Prefix: 'Mr.',
  Title: 'Programmer',
  City: 'Chatsworth',
  State: 'California',
  Email: 'wallyh@dx-email.com',
  Skype: 'wallyh_DX_skype',
  Mobile_Phone: '(818) 555-8872',
  Birth_Date: '1984-12-24',
  Hire_Date: '2011-02-17',
}, {
  ID: 24,
  Head_ID: 6,
  Full_Name: 'Brad Jameson',
  Prefix: 'Mr.',
  Title: 'Programmer',
  City: 'San Fernando',
  State: 'California',
  Email: 'bradleyj@dx-email.com',
  Skype: 'bradleyj_DX_skype',
  Mobile_Phone: '(818) 555-4646',
  Birth_Date: '1988-10-12',
  Hire_Date: '2011-03-02',
}, {
  ID: 25,
  Head_ID: 6,
  Full_Name: 'Karen Goodson',
  Prefix: 'Miss',
  Title: 'Programmer',
  City: 'South Pasadena',
  State: 'California',
  Email: 'kareng@dx-email.com',
  Skype: 'kareng_DX_skype',
  Mobile_Phone: '(626) 555-0908',
  Birth_Date: '1987-04-26',
  Hire_Date: '2011-03-14',
}, {
  ID: 26,
  Head_ID: 5,
  Full_Name: 'Marcus Orbison',
  Prefix: 'Mr.',
  Title: 'Travel Coordinator',
  City: 'Los Angeles',
  State: 'California',
  Email: 'marcuso@dx-email.com',
  Skype: 'marcuso_DX_skype',
  Mobile_Phone: '(213) 555-7098',
  Birth_Date: '1982-03-02',
  Hire_Date: '2005-05-19',
}, {
  ID: 27,
  Head_ID: 5,
  Full_Name: 'Sandy Bright',
  Prefix: 'Ms.',
  Title: 'Benefits Coordinator',
  City: 'Denver',
  State: 'Colorado',
  Email: 'sandrab@dx-email.com',
  Skype: 'sandrab_DX_skype',
  Mobile_Phone: '(818) 555-0524',
  Birth_Date: '1983-09-11',
  Hire_Date: '2005-06-04',
}, {
  ID: 28,
  Head_ID: 6,
  Full_Name: 'Morgan Kennedy',
  Prefix: 'Mrs.',
  Title: 'Graphic Designer',
  City: 'San Fernando Valley',
  State: 'California',
  Email: 'morgank@dx-email.com',
  Skype: 'morgank_DX_skype',
  Mobile_Phone: '(818) 555-8238',
  Birth_Date: '1984-07-17',
  Hire_Date: '2012-01-11',
}, {
  ID: 29,
  Head_ID: 28,
  Full_Name: 'Violet Bailey',
  Prefix: 'Ms.',
  Title: 'Jr Graphic Designer',
  City: 'La Canada',
  State: 'California',
  Email: 'violetb@dx-email.com',
  Skype: 'violetb_DX_skype',
  Mobile_Phone: '(818) 555-2478',
  Birth_Date: '1985-06-10',
  Hire_Date: '2012-01-19',
}, {
  ID: 30,
  Head_ID: 5,
  Full_Name: 'Ken Samuelson',
  Prefix: 'Dr.',
  Title: 'Ombudsman',
  City: 'St. Louis',
  State: 'Missouri',
  Email: 'kents@dx-email.com',
  Skype: 'kents_DX_skype',
  Mobile_Phone: '(562) 555-9282',
  Birth_Date: '1972-09-11',
  Hire_Date: '2009-04-22',
}];
