/*!
* DevExtreme (dx.messages.de.js)
* Version: 25.1.3
* Build date: Wed Jun 25 2025
*
* Copyright (c) 2012 - 2025 Developer Express Inc. ALL RIGHTS RESERVED
* Read about DevExtreme licensing here: https://js.devexpress.com/Licensing/
*/
"use strict";

! function (root, factory) {
    if ("function" === typeof define && define.amd) {
        define((function (require) {
            factory(require("devextreme/common/core/localization"))
        }))
    } else if ("object" === typeof module && module.exports) {
        factory(require("devextreme/common/core/localization"))
    } else {
        factory(DevExpress.localization)
    }
}(0, (function (localization) {
    localization.loadMessages({
        "sr-Latn": {
            "Yes": "Da",
            "No": "Ne",
            "Cancel": "Otkaži",
            "CheckState": "Proveri stanje",
            "Close": "Zatvori",
            "Clear": "Očisti",
            "Done": "Završeno",
            "Loading": "Učitavanje...",
            "Select": "Izaberi...",
            "Search": "Pretraga",
            "Back": "Nazad",
            "OK": "U redu",
            "Today": "Danas",
            "Yesterday": "Juče",
            "dxCollectionWidget-noDataText": "Nema podataka za prikaz",
            "dxDropDownEditor-selectLabel": "Izaberi",
            "validation-required": "Obavezno polje",
            "validation-required-formatted": "{0} je obavezno polje",
            "validation-numeric": "Vrednost mora biti broj",
            "validation-numeric-formatted": "{0} mora biti broj",
            "validation-range": "Vrednost je van dozvoljenog opsega",
            "validation-range-formatted": "{0} je van dozvoljenog opsega",
            "validation-stringLength": "Dužina vrednosti nije ispravna",
            "validation-stringLength-formatted": "Dužina za {0} nije ispravna",
            "validation-custom": "Vrednost nije ispravna",
            "validation-custom-formatted": "{0} nije ispravno",
            "validation-async": "Vrednost nije ispravna",
            "validation-async-formatted": "{0} nije ispravno",
            "validation-compare": "Vrednosti se ne podudaraju",
            "validation-compare-formatted": "{0} se ne podudara",
            "validation-pattern": "Vrednost ne odgovara obrascu",
            "validation-pattern-formatted": "{0} ne odgovara obrascu",
            "validation-email": "Email nije ispravan",
            "validation-email-formatted": "{0} nije ispravan",
            "validation-mask": "Vrednost nije ispravna",
            "dxLookup-searchPlaceholder": "Minimalan broj karaktera: {0}",
            "dxList-pullingDownText": "Prevucite nadole za osvežavanje...",
            "dxList-pulledDownText": "Otpustite za osvežavanje...",
            "dxList-refreshingText": "Osvežavanje...",
            "dxList-pageLoadingText": "Učitavanje...",
            "dxList-nextButtonText": "Još",
            "dxList-selectAll": "Izaberi sve",
            "dxList-listAriaLabel": "Stavke",
            "dxList-listAriaLabel-deletable": "Stavke koje se mogu obrisati",
            "dxListEditDecorator-delete": "Obriši",
            "dxListEditDecorator-more": "Više",
            "dxList-selectAll-indeterminate": "Delimično izabrano",
            "dxList-selectAll-checked": "Izabrano",
            "dxList-selectAll-notChecked": "Nije izabrano",
            "dxList-ariaRoleDescription": "Lista",
            "dxList-listAriaLabel-itemContent": "Sadržaj stavke u listi",
            "dxScrollView-pullingDownText": "Prevucite nadole za osvežavanje...",
            "dxScrollView-pulledDownText": "Otpustite za osvežavanje...",
            "dxScrollView-refreshingText": "Osvežavanje...",
            "dxScrollView-reachBottomText": "Učitavanje...",
            "dxDateBox-simulatedDataPickerTitleTime": "Izaberite vreme",
            "dxDateBox-simulatedDataPickerTitleDate": "Izaberite datum",
            "dxDateBox-simulatedDataPickerTitleDateTime": "Izaberite datum i vreme",
            "dxDateBox-validation-datetime": "Vrednost mora biti datum ili vreme",
            "dxDateRangeBox-invalidStartDateMessage": "Početna vrednost mora biti datum",
            "dxDateRangeBox-invalidEndDateMessage": "Krajnja vrednost mora biti datum",
            "dxDateRangeBox-startDateOutOfRangeMessage": "Početni datum je van opsega",
            "dxDateRangeBox-endDateOutOfRangeMessage": "Krajnji datum je van opsega",
            "dxDateRangeBox-startDateLabel": "Početni datum",
            "dxDateRangeBox-endDateLabel": "Krajnji datum",
            "dxFileUploader-selectFile": "Izaberi fajl",
            "dxFileUploader-dropFile": "ili prevucite fajl ovde",
            "dxFileUploader-bytes": "bajta",
            "dxFileUploader-kb": "KB",
            "dxFileUploader-Mb": "MB",
            "dxFileUploader-Gb": "GB",
            "dxFileUploader-upload": "Otpremi",
            "dxFileUploader-uploaded": "Otpremanje završeno",
            "dxFileUploader-readyToUpload": "Spremno za otpremanje",
            "dxFileUploader-uploadAbortedMessage": "Otpremanje otkazano",
            "dxFileUploader-uploadFailedMessage": "Otpremanje neuspešno",
            "dxFileUploader-invalidFileExtension": "Tip fajla nije dozvoljen",
            "dxFileUploader-invalidMaxFileSize": "Fajl je prevelik",
            "dxFileUploader-invalidMinFileSize": "Fajl je premali",
            "dxRangeSlider-ariaFrom": "Od",
            "dxRangeSlider-ariaTill": "Do",
            "dxSwitch-switchedOnText": "UKLJUČENO",
            "dxSwitch-switchedOffText": "ISKLJUČENO",
            "dxForm-optionalMark": "opciono",
            "dxForm-requiredMessage": "{0} je obavezno polje",
            "dxNumberBox-invalidValueMessage": "Vrednost mora biti broj",
            "dxNumberBox-noDataText": "Nema podataka",
            "dxDataGrid-emptyHeaderWithColumnChooserText": "Koristite {0} da prikažete kolone",
            "dxDataGrid-emptyHeaderWithGroupPanelText": "Prevucite kolonu iz panela za grupisanje ovde",
            "dxDataGrid-emptyHeaderWithColumnChooserAndGroupPanelText": "Koristite {0} ili prevucite kolonu iz panela za grupisanje",
            "dxDataGrid-emptyHeaderColumnChooserText": "izbor kolona",
            "dxDataGrid-columnChooserTitle": "Izbor kolona",
            "dxDataGrid-columnChooserEmptyText": "Prevucite kolonu ovde da biste je sakrili",
            "dxDataGrid-groupContinuesMessage": "Nastavlja se na sledećoj stranici",
            "dxDataGrid-groupContinuedMessage": "Nastavak sa prethodne stranice",
            "dxDataGrid-groupHeaderText": "Grupiši po ovoj koloni",
            "dxDataGrid-ungroupHeaderText": "Razgrupiši",
            "dxDataGrid-ungroupAllText": "Ukloni sve grupe",
            "dxDataGrid-editingEditRow": "Izmeni",
            "dxDataGrid-editingSaveRowChanges": "Sačuvaj",
            "dxDataGrid-editingCancelRowChanges": "Otkaži",
            "dxDataGrid-editingDeleteRow": "Obriši",
            "dxDataGrid-editingUndeleteRow": "Poništi brisanje",
            "dxDataGrid-editingConfirmDeleteMessage": "Da li ste sigurni da želite da obrišete ovaj zapis?",
            "dxDataGrid-validationCancelChanges": "Otkaži izmene",
            "dxDataGrid-groupPanelEmptyText": "Prevucite zaglavlje kolone ovde za grupisanje po toj koloni",
            "dxDataGrid-noDataText": "Nema podataka",
            "dxDataGrid-searchPanelPlaceholder": "Pretraga...",
            "dxDataGrid-filterRowShowAllText": "(Sve)",
            "dxDataGrid-filterRowResetOperationText": "Poništi",
            "dxDataGrid-filterRowOperationEquals": "Jednako",
            "dxDataGrid-filterRowOperationNotEquals": "Nije jednako",
            "dxDataGrid-filterRowOperationLess": "Manje od",
            "dxDataGrid-filterRowOperationLessOrEquals": "Manje ili jednako",
            "dxDataGrid-filterRowOperationGreater": "Veće od",
            "dxDataGrid-filterRowOperationGreaterOrEquals": "Veće ili jednako",
            "dxDataGrid-filterRowOperationStartsWith": "Počinje sa",
            "dxDataGrid-filterRowOperationContains": "Sadrži",
            "dxDataGrid-filterRowOperationNotContains": "Ne sadrži",
            "dxDataGrid-filterRowOperationEndsWith": "Završava se sa",
            "dxDataGrid-filterRowOperationBetween": "Između",
            "dxDataGrid-filterRowOperationBetweenStartText": "Početak",
            "dxDataGrid-filterRowOperationBetweenEndText": "Kraj",
            "dxDataGrid-ariaSearchBox": "Polje za pretragu",
            "dxDataGrid-applyFilterText": "Primeni filter",
            "dxDataGrid-trueText": "tačno",
            "dxDataGrid-falseText": "netačno",
            "dxDataGrid-sortingAscendingText": "Sortiraj rastuće",
            "dxDataGrid-sortingDescendingText": "Sortiraj opadajuće",
            "dxDataGrid-sortingClearText": "Obriši sortiranje",
            "dxDataGrid-ariaNotSortedColumn": "Kolona nije sortirana",
            "dxDataGrid-ariaSortedAscendingColumn": "Kolona sortirana rastuće",
            "dxDataGrid-ariaSortedDescendingColumn": "Kolona sortirana opadajuće",
            "dxDataGrid-ariaSortIndex": "Indeks sortiranja {0}",
            "dxDataGrid-editingSaveAllChanges": "Sačuvaj izmene",
            "dxDataGrid-editingCancelAllChanges": "Odbaci izmene",
            "dxDataGrid-editingAddRow": "Dodaj red",
            "dxDataGrid-summaryMin": "Min: {0}",
            "dxDataGrid-summaryMinOtherColumn": "Minimum za {1} je {0}",
            "dxDataGrid-summaryMax": "Maks: {0}",
            "dxDataGrid-summaryMaxOtherColumn": "Maksimum za {1} je {0}",
            "dxDataGrid-summaryAvg": "Prosek: {0}",
            "dxDataGrid-summaryAvgOtherColumn": "Prosek za {1} je {0}",
            "dxDataGrid-summarySum": "Zbir: {0}",
            "dxDataGrid-summarySumOtherColumn": "Zbir za {1} je {0}",
            "dxDataGrid-summaryCount": "Broj: {0}",
            "dxDataGrid-columnFixingFix": "Fiksiraj poziciju",
            "dxDataGrid-columnFixingUnfix": "Oslobodi fiksiranje",
            "dxDataGrid-columnFixingLeftPosition": "Levo",
            "dxDataGrid-columnFixingRightPosition": "Desno",
            "dxDataGrid-columnFixingStickyPosition": "Lepljivo",
            "dxDataGrid-exportTo": "Izvoz",
            "dxDataGrid-exportToExcel": "Izvezi u Excel fajl",
            "dxDataGrid-exporting": "Izvoženje...",
            "dxDataGrid-excelFormat": "Excel fajl",
            "dxDataGrid-selectedRows": "Izabrani redovi",
            "dxDataGrid-exportSelectedRows": "Izvezi izabrane redove u {0}",
            "dxDataGrid-exportAll": "Izvezi sve podatke u {0}",
            "dxDataGrid-headerFilterLabel": "Opcije filtriranja",
            "dxDataGrid-headerFilterIndicatorLabel": "Prikaži opcije filtera za kolonu '{0}'",
            "dxDataGrid-headerFilterEmptyValue": "(Prazno)",
            "dxDataGrid-headerFilterOK": "U redu",
            "dxDataGrid-headerFilterCancel": "Otkaži",
            "dxDataGrid-ariaAdaptiveCollapse": "Sakrij dodatne podatke",
            "dxDataGrid-ariaAdaptiveExpand": "Prikaži dodatne podatke",
            "dxDataGrid-ariaColumn": "Kolona",
            "dxDataGrid-ariaColumnHeader": "Zaglavlje kolone",
            "dxDataGrid-ariaValue": "Vrednost",
            "dxDataGrid-ariaError": "Greška",
            "dxDataGrid-ariaRevertButton": "Pritisnite Escape da odbacite izmene",
            "dxDataGrid-ariaFilterCell": "Ćelija za filter",
            "dxDataGrid-ariaCollapse": "Sažmi",
            "dxDataGrid-ariaModifiedCell": "Izmenjeno",
            "dxDataGrid-ariaDeletedCell": "Obrisano",
            "dxDataGrid-ariaEditableCell": "Može se menjati",
            "dxDataGrid-ariaExpand": "Proširi",
            "dxDataGrid-ariaCollapsedRow": "Sažeti red",
            "dxDataGrid-ariaExpandedRow": "Prošireni red",
            "dxDataGrid-ariaDataGrid": "Tabela sa {0} redova i {1} kolona",
            "dxDataGrid-ariaSearchInGrid": "Pretraži u tabeli",
            "dxDataGrid-ariaSelectAll": "Izaberi sve",
            "dxDataGrid-ariaSelectRow": "Izaberi red",
            "dxDataGrid-ariaToolbar": "Alatna traka tabele",
            "dxDataGrid-ariaEditForm": "Forma za izmenu",
            "dxDataGrid-filterBuilderPopupTitle": "Kreiranje filtera",
            "dxDataGrid-filterPanelCreateFilter": "Kreiraj filter",
            "dxDataGrid-filterPanelClearFilter": "Obriši",
            "dxDataGrid-filterPanelFilterEnabledHint": "Omogući filter",
            "dxDataGrid-masterDetail": "Ćelija sa detaljima",
            "dxDataGrid-moveColumnToTheRight": "Pomeri udesno",
            "dxDataGrid-moveColumnToTheLeft": "Pomeri ulevo",
            "dxTreeList-ariaTreeList": "Stablo sa {0} redova i {1} kolona",
            "dxTreeList-ariaExpandableInstruction": "Pritisnite Ctrl + strelica desno za proširenje čvora i Ctrl + strelica levo za sažimanje",
            "dxTreeList-ariaSearchInGrid": "Pretraži u stablu",
            "dxTreeList-ariaToolbar": "Alatna traka stabla",
            "dxTreeList-editingAddRowToNode": "Dodaj",
            "dxPager-infoText": "Strana {0} od {1} ({2} stavki)",
            "dxPager-pagesCountText": "od",
            "dxPager-pageSize": "Stavki po stranici: {0}",
            "dxPager-pageSizesAllText": "Sve",
            "dxPager-page": "Strana {0}",
            "dxPager-prevPage": "Prethodna strana",
            "dxPager-nextPage": "Sledeća strana",
            "dxPager-ariaLabel": "Navigacija kroz strane",
            "dxPager-ariaPageSize": "Veličina strane",
            "dxPager-ariaPageNumber": "Broj strane",
            "dxPagination-infoText": "Strana {0} od {1} ({2} stavki)",
            "dxPagination-pagesCountText": "od",
            "dxPagination-pageSize": "Stavki po stranici: {0}",
            "dxPagination-pageSizesAllText": "Sve",
            "dxPagination-page": "Strana {0}",
            "dxPagination-prevPage": "Prethodna strana",
            "dxPagination-nextPage": "Sledeća strana",
            "dxPagination-ariaLabel": "Navigacija kroz strane",
            "dxPagination-ariaPageSize": "Veličina strane",
            "dxPagination-ariaPageNumber": "Broj strane",
            "dxPivotGrid-grandTotal": "Ukupno",
            "dxPivotGrid-total": "Ukupno za {0}",
            "dxPivotGrid-fieldChooserTitle": "Izbor polja",
            "dxPivotGrid-showFieldChooser": "Prikaži izbor polja",
            "dxPivotGrid-expandAll": "Proširi sve",
            "dxPivotGrid-collapseAll": "Sažmi sve",
            "dxPivotGrid-sortColumnBySummary": "Sortiraj \"{0}\" po ovoj koloni",
            "dxPivotGrid-sortRowBySummary": "Sortiraj \"{0}\" po ovom redu",
            "dxPivotGrid-removeAllSorting": "Ukloni sve sortiranje",
            "dxPivotGrid-dataNotAvailable": "N/A",
            "dxPivotGrid-rowFields": "Polja reda",
            "dxPivotGrid-columnFields": "Polja kolone",
            "dxPivotGrid-dataFields": "Polja podataka",
            "dxPivotGrid-filterFields": "Polja filtera",
            "dxPivotGrid-allFields": "Sva polja",
            "dxPivotGrid-columnFieldArea": "Prevucite ovde kolone",
            "dxPivotGrid-dataFieldArea": "Prevucite ovde podatke",
            "dxPivotGrid-rowFieldArea": "Prevucite ovde redove",
            "dxPivotGrid-filterFieldArea": "Prevucite ovde filtere",
            "dxScheduler-dateRange": "od {0} do {1}",
            "dxScheduler-ariaLabel": "Planer. {0} prikaz: {1} sa {2} zakazanih stavki",
            "dxScheduler-ariaLabel-currentIndicator-present": "Trenutni indikator vremena je vidljiv u prikazu",
            "dxScheduler-ariaLabel-currentIndicator-not-present": "Trenutni indikator vremena nije vidljiv na ekranu",
            "dxScheduler-appointmentAriaLabel-group": "Grupa: {0}",
            "dxScheduler-appointmentAriaLabel-recurring": "Ponavljajući termin",
            "dxScheduler-appointmentListAriaLabel": "Lista termina",
            "dxScheduler-editorLabelTitle": "Tema",
            "dxScheduler-editorLabelStartDate": "Početni datum",
            "dxScheduler-editorLabelEndDate": "Krajnji datum",
            "dxScheduler-editorLabelDescription": "Opis",
            "dxScheduler-editorLabelRecurrence": "Ponavljanje",
            "dxScheduler-navigationToday": "Danas",
            "dxScheduler-navigationPrevious": "Prethodna strana",
            "dxScheduler-navigationNext": "Sledeća strana",
            "dxScheduler-openAppointment": "Otvori termin",
            "dxScheduler-recurrenceNever": "Nikada",
            "dxScheduler-recurrenceMinutely": "Svaki minut",
            "dxScheduler-recurrenceHourly": "Svaki sat",
            "dxScheduler-recurrenceDaily": "Dnevno",
            "dxScheduler-recurrenceWeekly": "Nedeljno",
            "dxScheduler-recurrenceMonthly": "Mesečno",
            "dxScheduler-recurrenceYearly": "Godišnje",
            "dxScheduler-recurrenceRepeatEvery": "Ponavljaj svakog",
            "dxScheduler-recurrenceRepeatOn": "Ponavljaj dana",
            "dxScheduler-recurrenceEnd": "Kraj ponavljanja",
            "dxScheduler-recurrenceAfter": "Nakon",
            "dxScheduler-recurrenceOn": "Na",
            "dxScheduler-recurrenceUntilDateLabel": "Datum završetka ponavljanja",
            "dxScheduler-recurrenceOccurrenceLabel": "Broj ponavljanja",
            "dxScheduler-recurrenceRepeatMinutely": "minut(a)",
            "dxScheduler-recurrenceRepeatHourly": "sat(i)",
            "dxScheduler-recurrenceRepeatDaily": "dan(a)",
            "dxScheduler-recurrenceRepeatWeekly": "nedelj(a)",
            "dxScheduler-recurrenceRepeatMonthly": "mesec(a)",
            "dxScheduler-recurrenceRepeatYearly": "godin(a)",
            "dxScheduler-switcherDay": "Dan",
            "dxScheduler-switcherWeek": "Nedelja",
            "dxScheduler-switcherWorkWeek": "Radna nedelja",
            "dxScheduler-switcherMonth": "Mesec",
            "dxScheduler-switcherAgenda": "Agenda",
            "dxScheduler-switcherTimelineDay": "Dnevna vremenska linija",
            "dxScheduler-switcherTimelineWeek": "Nedeljna vremenska linija",
            "dxScheduler-switcherTimelineWorkWeek": "Radna nedelja vremenska linija",
            "dxScheduler-switcherTimelineMonth": "Mesečna vremenska linija",
            "dxScheduler-recurrenceRepeatOnDate": "na datum",
            "dxScheduler-recurrenceRepeatCount": "ponavljanje(a)",
            "dxScheduler-allDay": "Ceodan",
            "dxScheduler-ariaEditForm": "Forma za izmenu",
            "dxScheduler-confirmRecurrenceEditTitle": "Izmeni ponavljajući termin",
            "dxScheduler-confirmRecurrenceDeleteTitle": "Obriši ponavljajući termin",
            "dxScheduler-confirmRecurrenceEditMessage": "Da li želite da izmenite samo ovaj termin ili celu seriju?",
            "dxScheduler-confirmRecurrenceDeleteMessage": "Da li želite da obrišete samo ovaj termin ili celu seriju?",
            "dxScheduler-confirmRecurrenceEditSeries": "Izmeni seriju",
            "dxScheduler-confirmRecurrenceDeleteSeries": "Obriši seriju",
            "dxScheduler-confirmRecurrenceEditOccurrence": "Izmeni termin",
            "dxScheduler-confirmRecurrenceDeleteOccurrence": "Obriši termin",
            "dxScheduler-noTimezoneTitle": "Bez vremenske zone",
            "dxScheduler-moreAppointments": "{0} više",
            "dxCalendar-currentDay": "Danas",
            "dxCalendar-currentMonth": "Tekući mesec",
            "dxCalendar-currentYear": "Tekuća godina",
            "dxCalendar-currentYearRange": "Tekući opseg godina",
            "dxCalendar-todayButtonText": "Danas",
            "dxCalendar-ariaWidgetName": "Kalendar",
            "dxCalendar-previousMonthButtonLabel": "Prethodni mesec",
            "dxCalendar-previousYearButtonLabel": "Prethodna godina",
            "dxCalendar-previousDecadeButtonLabel": "Prethodna decenija",
            "dxCalendar-previousCenturyButtonLabel": "Prethodni vek",
            "dxCalendar-nextMonthButtonLabel": "Sledeći mesec",
            "dxCalendar-nextYearButtonLabel": "Sledeća godina",
            "dxCalendar-nextDecadeButtonLabel": "Sledeća decenija",
            "dxCalendar-nextCenturyButtonLabel": "Sledeći vek",
            "dxCalendar-captionMonthLabel": "Izbor meseca",
            "dxCalendar-captionYearLabel": "Izbor godine",
            "dxCalendar-captionDecadeLabel": "Izbor decenije",
            "dxCalendar-captionCenturyLabel": "Izbor veka",
            "dxCalendar-selectedDate": "Izabrani datum je {0}",
            "dxCalendar-selectedDates": "Izabrani datumi",
            "dxCalendar-selectedDateRange": "Izabrani opseg datuma je od {0} do {1}",
            "dxCalendar-selectedMultipleDateRange": "od {0} do {1}",
            "dxCalendar-selectedDateRangeCount": "Postoji {0} izabranih opsega datuma",
            "dxCalendar-readOnlyLabel": "Kalendar samo za čitanje",
            "dxCardView-ariaSearchInGrid": "Pretraga u prikazu kartica",
            "dxCardView-ariaHeaderItemLabel": "Naziv polja {0}",
            "dxCardView-ariaHeaderItemSortingAscendingLabel": "Sortirano rastuće",
            "dxCardView-ariaHeaderItemSortingDescendingLabel": "Sortirano opadajuće",
            "dxCardView-ariaHeaderItemSortingIndexLabel": "Indeks sortiranja {0}",
            "dxCardView-ariaHeaderHasHeaderFilterLabel": "Primijenjen filter zaglavlja",
            "dxCardView-ariaSelectCard": "Izaberi karticu",
            "dxCardView-ariaCardView": "Prikaz kartica sa {0} kartica. Svaka kartica ima {1} polja",
            "dxCardView-ariaCard": "Kartica",
            "dxCardView-ariaEditableCard": "Kartica se može menjati",
            "dxCardView-ariaCardPosition": "Red {0}, kolona {1}",
            "dxCardView-ariaSelectedCardState": "Izabrana",
            "dxCardView-ariaNotSelectedCardState": "Nije izabrana",
            "dxCardView-selectAll": "Izaberi sve",
            "dxCardView-clearSelection": "Poništi izbor",
            "dxCardView-cardNoImageAriaLabel": "Bez slike",
            "dxCardView-headerItemDropZoneText": "Prevucite ovde zaglavlje stavke",
            "dxCardView-emptyHeaderPanelText": "Koristite {0} za prikaz kolona",
            "dxCardView-emptyHeaderPanelColumnChooserText": "izbor kolona",
            "dxAvatar-defaultImageAlt": "Avatar",
            "dxChat-elementAriaLabel": "Ćaskanje",
            "dxChat-textareaPlaceholder": "Unesite poruku",
            "dxChat-sendButtonAriaLabel": "Pošalji",
            "dxChat-cancelEditingButtonAriaLabel": "Otkaži",
            "dxChat-editingMessageCaption": "Izmeni poruku",
            "dxChat-defaultUserName": "Nepoznat korisnik",
            "dxChat-messageListAriaLabel": "Lista poruka",
            "dxChat-alertListAriaLabel": "Lista grešaka",
            "dxChat-emptyListMessage": "Nema poruka u ovom ćaskanju",
            "dxChat-emptyListPrompt": "Napišite svoju prvu poruku",
            "dxChat-typingMessageSingleUser": "{0} kuca...",
            "dxChat-typingMessageTwoUsers": "{0} i {1} kucaju...",
            "dxChat-typingMessageThreeUsers": "{0}, {1} i {2} kucaju...",
            "dxChat-typingMessageMultipleUsers": "{0} i ostali kucaju...",
            "dxChat-editedMessageText": "Izmenjeno",
            "dxChat-editingEditMessage": "Izmeni",
            "dxChat-editingDeleteMessage": "Obriši",
            "dxChat-editingDeleteConfirmText": "Da li ste sigurni da želite da obrišete ovu poruku?",
            "dxChat-deletedMessageText": "Poruka je obrisana",
            "dxChat-defaultImageAlt": "Slika podeljena u ćaskanju",
            "dxColorView-ariaRed": "Crvena",
            "dxColorView-ariaGreen": "Zelena",
            "dxColorView-ariaBlue": "Plava",
            "dxColorView-ariaAlpha": "Providnost",
            "dxColorView-ariaHex": "Kod boje",
            "dxTagBox-selected": "{0} izabrano",
            "dxTagBox-allSelected": "Sve izabrano ({0})",
            "dxTagBox-moreSelected": "{0} više",
            "dxTagBox-tagRoleDescription": "Oznaka. Pritisnite dugme za brisanje da uklonite ovu oznaku",
            "dxTagBox-ariaRoleDescription": "Polje za oznake",
            "vizExport-printingButtonText": "Štampaj",
            "vizExport-titleMenuText": "Izvoz/Štampa",
            "vizExport-exportButtonText": "{0} fajl",
            "dxFilterBuilder-and": "I",
            "dxFilterBuilder-or": "Ili",
            "dxFilterBuilder-notAnd": "Ne i",
            "dxFilterBuilder-notOr": "Ne ili",
            "dxFilterBuilder-addCondition": "Dodaj uslov",
            "dxFilterBuilder-addGroup": "Dodaj grupu",
            "dxFilterBuilder-enterValueText": "<unesi vrednost>",
            "dxFilterBuilder-filterOperationEquals": "Jednako",
            "dxFilterBuilder-filterOperationNotEquals": "Nije jednako",
            "dxFilterBuilder-filterOperationLess": "Manje od",
            "dxFilterBuilder-filterOperationLessOrEquals": "Manje ili jednako",
            "dxFilterBuilder-filterOperationGreater": "Veće od",
            "dxFilterBuilder-filterOperationGreaterOrEquals": "Veće ili jednako",
            "dxFilterBuilder-filterOperationStartsWith": "Počinje sa",
            "dxFilterBuilder-filterOperationContains": "Sadrži",
            "dxFilterBuilder-filterOperationNotContains": "Ne sadrži",
            "dxFilterBuilder-filterOperationEndsWith": "Završava se sa",
            "dxFilterBuilder-filterOperationIsBlank": "Je prazno",
            "dxFilterBuilder-filterOperationIsNotBlank": "Nije prazno",
            "dxFilterBuilder-filterOperationBetween": "Između",
            "dxFilterBuilder-filterOperationAnyOf": "Bilo koji od",
            "dxFilterBuilder-filterOperationNoneOf": "Nijedan od",
            "dxFilterBuilder-filterAriaRootElement": "Kreator filtera",
            "dxFilterBuilder-filterAriaGroupLevel": "Nivo {0}",
            "dxFilterBuilder-filterAriaGroupItem": "Stavka grupe",
            "dxFilterBuilder-filterAriaOperationButton": "Operacija",
            "dxFilterBuilder-filterAriaAddButton": "Dodaj",
            "dxFilterBuilder-filterAriaRemoveButton": "Ukloni {0}",
            "dxFilterBuilder-filterAriaItemField": "Polje stavke",
            "dxFilterBuilder-filterAriaItemOperation": "Operacija stavke",
            "dxFilterBuilder-filterAriaItemValue": "Vrednost stavke",
            "dxHtmlEditor-dialogColorCaption": "Promeni boju fonta",
            "dxHtmlEditor-dialogBackgroundCaption": "Promeni boju pozadine",
            "dxHtmlEditor-dialogLinkCaption": "Dodaj link",
            "dxHtmlEditor-dialogLinkUrlField": "URL",
            "dxHtmlEditor-dialogLinkTextField": "Tekst",
            "dxHtmlEditor-dialogLinkTargetField": "Otvori link u novom prozoru",
            "dxHtmlEditor-dialogImageCaption": "Dodaj sliku",
            "dxHtmlEditor-dialogImageUrlField": "URL",
            "dxHtmlEditor-dialogImageAltField": "Alternativni tekst",
            "dxHtmlEditor-dialogImageWidthField": "Širina (px)",
            "dxHtmlEditor-dialogImageHeightField": "Visina (px)",
            "dxHtmlEditor-dialogInsertTableRowsField": "Redovi",
            "dxHtmlEditor-dialogInsertTableColumnsField": "Kolone",
            "dxHtmlEditor-dialogInsertTableCaption": "Ubaci tabelu",
            "dxHtmlEditor-dialogUpdateImageCaption": "Ažuriraj sliku",
            "dxHtmlEditor-dialogImageUpdateButton": "Ažuriraj",
            "dxHtmlEditor-dialogImageAddButton": "Dodaj",
            "dxHtmlEditor-dialogImageSpecifyUrl": "Sa interneta",
            "dxHtmlEditor-dialogImageSelectFile": "Sa ovog uređaja",
            "dxHtmlEditor-dialogImageKeepAspectRatio": "Zadrži proporcije",
            "dxHtmlEditor-dialogImageEncodeToBase64": "Kodiraj u Base64",
            "dxHtmlEditor-heading": "Naslov",
            "dxHtmlEditor-normalText": "Običan tekst",
            "dxHtmlEditor-background": "Boja pozadine",
            "dxHtmlEditor-bold": "Podebljano",
            "dxHtmlEditor-color": "Boja fonta",
            "dxHtmlEditor-font": "Font",
            "dxHtmlEditor-italic": "Kurziv",
            "dxHtmlEditor-link": "Dodaj link",
            "dxHtmlEditor-image": "Dodaj sliku",
            "dxHtmlEditor-size": "Veličina",
            "dxHtmlEditor-strike": "Precrtano",
            "dxHtmlEditor-subscript": "Indeks dolje",
            "dxHtmlEditor-superscript": "Indeks gore",
            "dxHtmlEditor-underline": "Podvučeno",
            "dxHtmlEditor-blockquote": "Citat",
            "dxHtmlEditor-header": "Zaglavlje",
            "dxHtmlEditor-increaseIndent": "Povećaj uvlačenje",
            "dxHtmlEditor-decreaseIndent": "Smanji uvlačenje",
            "dxHtmlEditor-orderedList": "Numerisana lista",
            "dxHtmlEditor-bulletList": "Lista sa znakovima",
            "dxHtmlEditor-alignLeft": "Poravnaj levo",
            "dxHtmlEditor-alignCenter": "Poravnaj centar",
            "dxHtmlEditor-alignRight": "Poravnaj desno",
            "dxHtmlEditor-alignJustify": "Poravnaj obostrano",
            "dxHtmlEditor-codeBlock": "Blok koda",
            "dxHtmlEditor-variable": "Dodaj promenljivu",
            "dxHtmlEditor-undo": "Poništi",
            "dxHtmlEditor-redo": "Ponovi",
            "dxHtmlEditor-clear": "Ukloni formatiranje",
            "dxHtmlEditor-insertTable": "Ubaci tabelu",
            "dxHtmlEditor-insertHeaderRow": "Ubaci red zaglavlja",
            "dxHtmlEditor-insertRowAbove": "Ubaci red iznad",
            "dxHtmlEditor-insertRowBelow": "Ubaci red ispod",
            "dxHtmlEditor-insertColumnLeft": "Ubaci kolonu levo",
            "dxHtmlEditor-insertColumnRight": "Ubaci kolonu desno",
            "dxHtmlEditor-deleteColumn": "Obriši kolonu",
            "dxHtmlEditor-deleteRow": "Obriši red",
            "dxHtmlEditor-deleteTable": "Obriši tabelu",
            "dxHtmlEditor-cellProperties": "Osobine ćelije",
            "dxHtmlEditor-tableProperties": "Osobine tabele",
            "dxHtmlEditor-insert": "Ubaci",
            "dxHtmlEditor-delete": "Obriši",
            "dxHtmlEditor-border": "Ivica",
            "dxHtmlEditor-style": "Stil",
            "dxHtmlEditor-width": "Širina",
            "dxHtmlEditor-height": "Visina",
            "dxHtmlEditor-borderColor": "Boja",
            "dxHtmlEditor-borderWidth": "Debljina ivice",
            "dxHtmlEditor-tableBackground": "Pozadina",
            "dxHtmlEditor-dimensions": "Dimenzije",
            "dxHtmlEditor-alignment": "Poravnanje",
            "dxHtmlEditor-horizontal": "Horizontalno",
            "dxHtmlEditor-vertical": "Vertikalno",
            "dxHtmlEditor-paddingVertical": "Vertikalno razmak",
            "dxHtmlEditor-paddingHorizontal": "Horizontalni razmak",
            "dxHtmlEditor-pixels": "Pikseli",
            "dxHtmlEditor-list": "Lista",
            "dxHtmlEditor-ordered": "Numerisana",
            "dxHtmlEditor-bullet": "Sa znakovima",
            "dxHtmlEditor-align": "Poravnaj",
            "dxHtmlEditor-center": "Centar",
            "dxHtmlEditor-left": "Levo",
            "dxHtmlEditor-right": "Desno",
            "dxHtmlEditor-indent": "Uvuci",
            "dxHtmlEditor-justify": "Obostrano",
            "dxHtmlEditor-borderStyleNone": "bez ivice",
            "dxHtmlEditor-borderStyleHidden": "skrivena",
            "dxHtmlEditor-borderStyleDotted": "tačkasta",
            "dxHtmlEditor-borderStyleDashed": "isprekidana",
            "dxHtmlEditor-borderStyleSolid": "puna",
            "dxHtmlEditor-borderStyleDouble": "dupla",
            "dxHtmlEditor-borderStyleGroove": "urezana",
            "dxHtmlEditor-borderStyleRidge": "ispupčena",
            "dxHtmlEditor-borderStyleInset": "unutra",
            "dxHtmlEditor-borderStyleOutset": "napolje",
            "dxHtmlEditor-aiDialogTitle": "AI Asistent",
            "dxHtmlEditor-aiDialogError": "Nešto nije u redu. Pokušajte ponovo.",
            "dxHtmlEditor-aiDialogCanceled": "Generisanje otkazano",
            "dxHtmlEditor-aiReplace": "Zameni",
            "dxHtmlEditor-aiInsertAbove": "Ubaci iznad",
            "dxHtmlEditor-aiInsertBelow": "Ubaci ispod",
            "dxHtmlEditor-aiCopy": "Kopiraj",
            "dxHtmlEditor-aiRegenerate": "Generiši ponovo",
            "dxHtmlEditor-aiGenerate": "Generiši",
            "dxHtmlEditor-aiCancel": "Otkaži",
            "dxHtmlEditor-aiToolbarItemAriaLabel": "Stavka alatne trake AI asistenta",
            "dxHtmlEditor-aiResultTextAreaAriaLabel": "Rezultat AI asistenta",
            "dxHtmlEditor-aiAskPlaceholder": "Zatraži od AI da izmeni tekst",
            "dxFileManager-newDirectoryName": "Neimenovani direktorijum",
            "dxFileManager-rootDirectoryName": "Fajlovi",
            "dxFileManager-errorNoAccess": "Pristup odbijen. Operacija nije mogla biti izvršena.",
            "dxFileManager-errorDirectoryExistsFormat": "Direktorijum '{0}' već postoji.",
            "dxFileManager-errorFileExistsFormat": "Fajl '{0}' već postoji.",
            "dxFileManager-errorFileNotFoundFormat": "Fajl '{0}' nije pronađen.",
            "dxFileManager-errorDirectoryNotFoundFormat": "Direktorijum '{0}' nije pronađen.",
            "dxFileManager-errorWrongFileExtension": "Ekstenzija fajla nije dozvoljena.",
            "dxFileManager-errorMaxFileSizeExceeded": "Veličina fajla prelazi dozvoljeni maksimum.",
            "dxFileManager-errorInvalidSymbols": "Naziv sadrži nedozvoljene karaktere.",
            "dxFileManager-errorDefault": "Nedefinisana greška.",
            "dxFileManager-errorDirectoryOpenFailed": "Direktorijum ne može biti otvoren",
            "dxFileManager-commandCreate": "Novi direktorijum",
            "dxFileManager-commandRename": "Preimenuj",
            "dxFileManager-commandMove": "Premesti u",
            "dxFileManager-commandCopy": "Kopiraj u",
            "dxFileManager-commandDelete": "Obriši",
            "dxFileManager-commandDownload": "Preuzmi",
            "dxFileManager-commandUpload": "Otpremi fajlove",
            "dxFileManager-commandRefresh": "Osveži",
            "dxFileManager-commandThumbnails": "Prikaz sličica",
            "dxFileManager-commandDetails": "Detaljan prikaz",
            "dxFileManager-commandClearSelection": "Poništi izbor",
            "dxFileManager-commandShowNavPane": "Prikaži/sakrij navigaciju",
            "dxFileManager-dialogDirectoryChooserMoveTitle": "Premesti u",
            "dxFileManager-dialogDirectoryChooserMoveButtonText": "Premesti",
            "dxFileManager-dialogDirectoryChooserCopyTitle": "Kopiraj u",
            "dxFileManager-dialogDirectoryChooserCopyButtonText": "Kopiraj",
            "dxFileManager-dialogRenameItemTitle": "Preimenuj",
            "dxFileManager-dialogRenameItemButtonText": "Sačuvaj",
            "dxFileManager-dialogCreateDirectoryTitle": "Novi direktorijum",
            "dxFileManager-dialogCreateDirectoryButtonText": "Kreiraj",
            "dxFileManager-dialogDeleteItemTitle": "Obriši",
            "dxFileManager-dialogDeleteItemButtonText": "Obriši",
            "dxFileManager-dialogDeleteItemSingleItemConfirmation": "Da li ste sigurni da želite da obrišete {0}?",
            "dxFileManager-dialogDeleteItemMultipleItemsConfirmation": "Da li ste sigurni da želite da obrišete {0} stavki?",
            "dxFileManager-dialogButtonCancel": "Otkaži",
            "dxFileManager-editingCreateSingleItemProcessingMessage": "Kreiranje direktorijuma u {0}",
            "dxFileManager-editingCreateSingleItemSuccessMessage": "Direktorijum je kreiran u {0}",
            "dxFileManager-editingCreateSingleItemErrorMessage": "Direktorijum nije kreiran",
            "dxFileManager-editingCreateCommonErrorMessage": "Direktorijum nije kreiran",
            "dxFileManager-editingRenameSingleItemProcessingMessage": "Preimenovanje stavke u {0}",
            "dxFileManager-editingRenameSingleItemSuccessMessage": "Stavka je preimenovana u {0}",
            "dxFileManager-editingRenameSingleItemErrorMessage": "Stavka nije preimenovana",
            "dxFileManager-editingRenameCommonErrorMessage": "Stavka nije preimenovana",
            "dxFileManager-editingDeleteSingleItemProcessingMessage": "Brisanje stavke iz {0}",
            "dxFileManager-editingDeleteMultipleItemsProcessingMessage": "Brisanje {0} stavki iz {1}",
            "dxFileManager-editingDeleteSingleItemSuccessMessage": "Stavka obrisana iz {0}",
            "dxFileManager-editingDeleteMultipleItemsSuccessMessage": "{0} stavki obrisano iz {1}",
            "dxFileManager-editingDeleteSingleItemErrorMessage": "Stavka nije obrisana",
            "dxFileManager-editingDeleteMultipleItemsErrorMessage": "{0} stavki nije obrisano",
            "dxFileManager-editingDeleteCommonErrorMessage": "Neke stavke nisu obrisane",
            "dxFileManager-editingMoveSingleItemProcessingMessage": "Premještanje stavke u {0}",
            "dxFileManager-editingMoveMultipleItemsProcessingMessage": "Premještanje {0} stavki u {1}",
            "dxFileManager-editingMoveSingleItemSuccessMessage": "Stavka premještena u {0}",
            "dxFileManager-editingMoveMultipleItemsSuccessMessage": "{0} stavki premješteno u {1}",
            "dxFileManager-editingMoveSingleItemErrorMessage": "Stavka nije premještena",
            "dxFileManager-editingMoveMultipleItemsErrorMessage": "{0} stavki nije premješteno",
            "dxFileManager-editingMoveCommonErrorMessage": "Neke stavke nisu premještene",
            "dxFileManager-editingCopySingleItemProcessingMessage": "Kopiranje stavke u {0}",
            "dxFileManager-editingCopyMultipleItemsProcessingMessage": "Kopiranje {0} stavki u {1}",
            "dxFileManager-editingCopySingleItemSuccessMessage": "Stavka kopirana u {0}",
            "dxFileManager-editingCopyMultipleItemsSuccessMessage": "{0} stavki kopirano u {1}",
            "dxFileManager-editingCopySingleItemErrorMessage": "Stavka nije kopirana",
            "dxFileManager-editingCopyMultipleItemsErrorMessage": "{0} stavki nije kopirano",
            "dxFileManager-editingCopyCommonErrorMessage": "Neke stavke nisu kopirane",
            "dxFileManager-editingUploadSingleItemProcessingMessage": "Otpremanje stavke u {0}",
            "dxFileManager-editingUploadMultipleItemsProcessingMessage": "Otpremanje {0} stavki u {1}",
            "dxFileManager-editingUploadSingleItemSuccessMessage": "Stavka otpremljena u {0}",
            "dxFileManager-editingUploadMultipleItemsSuccessMessage": "{0} stavki otpremljeno u {1}",
            "dxFileManager-editingUploadSingleItemErrorMessage": "Stavka nije otpremljena",
            "dxFileManager-editingUploadMultipleItemsErrorMessage": "{0} stavki nije otpremljeno",
            "dxFileManager-editingUploadCanceledMessage": "Otkazano",
            "dxFileManager-editingDownloadSingleItemErrorMessage": "Stavka nije preuzeta",
            "dxFileManager-editingDownloadMultipleItemsErrorMessage": "{0} stavki nije preuzeto",
            "dxFileManager-listDetailsColumnCaptionName": "Naziv",
            "dxFileManager-listDetailsColumnCaptionDateModified": "Datum izmene",
            "dxFileManager-listDetailsColumnCaptionFileSize": "Veličina fajla",
            "dxFileManager-listThumbnailsTooltipTextSize": "Veličina",
            "dxFileManager-listThumbnailsTooltipTextDateModified": "Datum izmene",
            "dxFileManager-notificationProgressPanelTitle": "Napredak",
            "dxFileManager-notificationProgressPanelEmptyListText": "Nema operacija",
            "dxFileManager-notificationProgressPanelOperationCanceled": "Otkazano",
            "dxDiagram-categoryGeneral": "Opšte",
            "dxDiagram-categoryFlowchart": "Dijagram toka",
            "dxDiagram-categoryOrgChart": "Organizaciona šema",
            "dxDiagram-categoryContainers": "Kontejneri",
            "dxDiagram-categoryCustom": "Prilagođeno",
            "dxDiagram-commandExportToSvg": "Izvezi u SVG",
            "dxDiagram-commandExportToPng": "Izvezi u PNG",
            "dxDiagram-commandExportToJpg": "Izvezi u JPEG",
            "dxDiagram-commandUndo": "Poništi",
            "dxDiagram-commandRedo": "Ponovi",
            "dxDiagram-commandFontName": "Naziv fonta",
            "dxDiagram-commandFontSize": "Veličina fonta",
            "dxDiagram-commandBold": "Podebljano",
            "dxDiagram-commandItalic": "Kurziv",
            "dxDiagram-commandUnderline": "Podvučeno",
            "dxDiagram-commandTextColor": "Boja fonta",
            "dxDiagram-commandLineColor": "Boja linije",
            "dxDiagram-commandLineWidth": "Širina linije",
            "dxDiagram-commandLineStyle": "Stil linije",
            "dxDiagram-commandLineStyleSolid": "Puna",
            "dxDiagram-commandLineStyleDotted": "Tačkasta",
            "dxDiagram-commandLineStyleDashed": "Isprekidana",
            "dxDiagram-commandFillColor": "Boja ispune",
            "dxDiagram-commandAlignLeft": "Poravnaj levo",
            "dxDiagram-commandAlignCenter": "Poravnaj centar",
            "dxDiagram-commandAlignRight": "Poravnaj desno",
            "dxDiagram-commandConnectorLineType": "Tip linije konektora",
            "dxDiagram-commandConnectorLineStraight": "Prava",
            "dxDiagram-commandConnectorLineOrthogonal": "Ortogonalna",
            "dxDiagram-commandConnectorLineStart": "Početak konektora",
            "dxDiagram-commandConnectorLineEnd": "Kraj konektora",
            "dxDiagram-commandConnectorLineNone": "Bez",
            "dxDiagram-commandConnectorLineArrow": "Strelica",
            "dxDiagram-commandFullscreen": "Ceo ekran",
            "dxDiagram-commandUnits": "Jedinice",
            "dxDiagram-commandPageSize": "Veličina stranice",
            "dxDiagram-commandPageOrientation": "Orijentacija stranice",
            "dxDiagram-commandPageOrientationLandscape": "Pejzaž",
            "dxDiagram-commandPageOrientationPortrait": "Portret",
            "dxDiagram-commandPageColor": "Boja stranice",
            "dxDiagram-commandShowGrid": "Prikaži mrežu",
            "dxDiagram-commandSnapToGrid": "Poravnaj na mrežu",
            "dxDiagram-commandGridSize": "Veličina mreže",
            "dxDiagram-commandZoomLevel": "Nivo uveličanja",
            "dxDiagram-commandAutoZoom": "Automatsko uveličanje",
            "dxDiagram-commandFitToContent": "Prilagodi sadržaju",
            "dxDiagram-commandFitToWidth": "Prilagodi širini",
            "dxDiagram-commandAutoZoomByContent": "Auto zumiraj po sadržaju",
            "dxDiagram-commandAutoZoomByWidth": "Auto zumiraj po širini",
            "dxDiagram-commandSimpleView": "Jednostavan prikaz",
            "dxDiagram-commandCut": "Iseci",
            "dxDiagram-commandCopy": "Kopiraj",
            "dxDiagram-commandPaste": "Nalepi",
            "dxDiagram-commandSelectAll": "Izaberi sve",
            "dxDiagram-commandDelete": "Obriši",
            "dxDiagram-commandBringToFront": "Stavi u prvi plan",
            "dxDiagram-commandSendToBack": "Stavi u pozadinu",
            "dxDiagram-commandLock": "Zaključaj",
            "dxDiagram-commandUnlock": "Otključaj",
            "dxDiagram-commandInsertShapeImage": "Ubaci sliku...",
            "dxDiagram-commandEditShapeImage": "Izmeni sliku...",
            "dxDiagram-commandDeleteShapeImage": "Obriši sliku",
            "dxDiagram-commandLayoutLeftToRight": "S leva na desno",
            "dxDiagram-commandLayoutRightToLeft": "S desna na levo",
            "dxDiagram-commandLayoutTopToBottom": "Od gore ka dole",
            "dxDiagram-commandLayoutBottomToTop": "Od dole ka gore",
            "dxDiagram-unitIn": "in",
            "dxDiagram-unitCm": "cm",
            "dxDiagram-unitPx": "px",
            "dxDiagram-dialogButtonOK": "U redu",
            "dxDiagram-dialogButtonCancel": "Otkaži",
            "dxDiagram-dialogInsertShapeImageTitle": "Ubaci sliku",
            "dxDiagram-dialogEditShapeImageTitle": "Izmeni sliku",
            "dxDiagram-dialogEditShapeImageSelectButton": "Izaberi sliku",
            "dxDiagram-dialogEditShapeImageLabelText": "ili prevucite fajl ovde",
            "dxDiagram-uiExport": "Izvezi",
            "dxDiagram-uiProperties": "Svojstva",
            "dxDiagram-uiSettings": "Podešavanja",
            "dxDiagram-uiShowToolbox": "Prikaži alatku",
            "dxDiagram-uiSearch": "Pretraga",
            "dxDiagram-uiStyle": "Stil",
            "dxDiagram-uiLayout": "Raspored",
            "dxDiagram-uiLayoutTree": "Stablo",
            "dxDiagram-uiLayoutLayered": "Slojevito",
            "dxDiagram-uiDiagram": "Dijagram",
            "dxDiagram-uiText": "Tekst",
            "dxDiagram-uiObject": "Objekat",
            "dxDiagram-uiConnector": "Konektor",
            "dxDiagram-uiPage": "Stranica",
            "dxDiagram-shapeText": "Tekst",
            "dxDiagram-shapeRectangle": "Pravougaonik",
            "dxDiagram-shapeEllipse": "Elipsa",
            "dxDiagram-shapeCross": "Krst",
            "dxDiagram-shapeTriangle": "Trougao",
            "dxDiagram-shapeDiamond": "Dijamant",
            "dxDiagram-shapeHeart": "Srce",
            "dxDiagram-shapePentagon": "Petougao",
            "dxDiagram-shapeHexagon": "Šestougao",
            "dxDiagram-shapeOctagon": "Osmougao",
            "dxDiagram-shapeStar": "Zvezda",
            "dxDiagram-shapeArrowLeft": "Strelica levo",
            "dxDiagram-shapeArrowUp": "Strelica gore",
            "dxDiagram-shapeArrowRight": "Strelica desno",
            "dxDiagram-shapeArrowDown": "Strelica dole",
            "dxDiagram-shapeArrowUpDown": "Strelica gore-dole",
            "dxDiagram-shapeArrowLeftRight": "Strelica levo-desno",
            "dxDiagram-shapeProcess": "Proces",
            "dxDiagram-shapeDecision": "Odluka",
            "dxDiagram-shapeTerminator": "Terminator",
            "dxDiagram-shapePredefinedProcess": "Predefinisani proces",
            "dxDiagram-shapeDocument": "Dokument",
            "dxDiagram-shapeMultipleDocuments": "Više dokumenata",
            "dxDiagram-shapeManualInput": "Ručno unošenje",
            "dxDiagram-shapePreparation": "Priprema",
            "dxDiagram-shapeData": "Podatak",
            "dxDiagram-shapeDatabase": "Baza podataka",
            "dxDiagram-shapeHardDisk": "Hard disk",
            "dxDiagram-shapeInternalStorage": "Interna memorija",
            "dxDiagram-shapePaperTape": "Papirna traka",
            "dxDiagram-shapeManualOperation": "Ručna operacija",
            "dxDiagram-shapeDelay": "Kašnjenje",
            "dxDiagram-shapeStoredData": "Skladišteni podaci",
            "dxDiagram-shapeDisplay": "Prikaz",
            "dxDiagram-shapeMerge": "Spajanje",
            "dxDiagram-shapeConnector": "Konektor",
            "dxDiagram-shapeOr": "Ili",
            "dxDiagram-shapeSummingJunction": "Spojna tačka sabiranja",
            "dxDiagram-shapeContainerDefaultText": "Kontejner",
            "dxDiagram-shapeVerticalContainer": "Vertikalni kontejner",
            "dxDiagram-shapeHorizontalContainer": "Horizontalni kontejner",
            "dxDiagram-shapeCardDefaultText": "Ime osobe",
            "dxDiagram-shapeCardWithImageOnLeft": "Kartica sa slikom levo",
            "dxDiagram-shapeCardWithImageOnTop": "Kartica sa slikom gore",
            "dxDiagram-shapeCardWithImageOnRight": "Kartica sa slikom desno",
            "dxGantt-dialogTitle": "Naslov",
            "dxGantt-dialogStartTitle": "Početak",
            "dxGantt-dialogEndTitle": "Kraj",
            "dxGantt-dialogProgressTitle": "Napredak",
            "dxGantt-dialogResourcesTitle": "Resursi",
            "dxGantt-dialogResourceManagerTitle": "Menadžer resursa",
            "dxGantt-dialogTaskDetailsTitle": "Detalji zadatka",
            "dxGantt-dialogEditResourceListHint": "Izmeni listu resursa",
            "dxGantt-dialogEditNoResources": "Nema resursa",
            "dxGantt-dialogButtonAdd": "Dodaj",
            "dxGantt-contextMenuNewTask": "Novi zadatak",
            "dxGantt-contextMenuNewSubtask": "Novi podzadatak",
            "dxGantt-contextMenuDeleteTask": "Obriši zadatak",
            "dxGantt-contextMenuDeleteDependency": "Obriši zavisnost",
            "dxGantt-dialogTaskDeleteConfirmation": "Brisanjem zadatka brišu se i njegove zavisnosti i podzaci. Da li ste sigurni da želite da obrišete ovaj zadatak?",
            "dxGantt-dialogDependencyDeleteConfirmation": "Da li ste sigurni da želite da obrišete zavisnost ovog zadatka?",
            "dxGantt-dialogResourcesDeleteConfirmation": "Brisanjem resursa on će biti uklonjen iz svih povezanih zadataka. Da li ste sigurni da želite da obrišete sledeće resurse? Resursi: {0}",
            "dxGantt-dialogConstraintCriticalViolationMessage": "Zadatak koji pokušavate da pomerite je povezan sa drugim zadatkom i promena bi prekršila pravila zavisnosti. Kako želite da nastavite?",
            "dxGantt-dialogConstraintViolationMessage": "Zadatak koji pokušavate da pomerite je povezan sa drugim zadatkom. Kako želite da nastavite?",
            "dxGantt-dialogCancelOperationMessage": "Otkaži operaciju",
            "dxGantt-dialogDeleteDependencyMessage": "Obriši zavisnost",
            "dxGantt-dialogMoveTaskAndKeepDependencyMessage": "Pomeri zadatak i zadrži zavisnost",
            "dxGantt-dialogConstraintCriticalViolationSeveralTasksMessage": "Zadatak koji pokušavate da pomerite povezan je sa više drugih zadataka. Ova promena bi prekršila pravila zavisnosti. Kako želite da nastavite?",
            "dxGantt-dialogConstraintViolationSeveralTasksMessage": "Zadatak koji pokušavate da pomerite povezan je sa više drugih zadataka. Kako želite da nastavite?",
            "dxGantt-dialogDeleteDependenciesMessage": "Obriši sve zavisnosti",
            "dxGantt-dialogMoveTaskAndKeepDependenciesMessage": "Pomeri zadatak i zadrži sve zavisnosti",
            "dxGantt-undo": "Poništi",
            "dxGantt-redo": "Ponovi",
            "dxGantt-expandAll": "Proširi sve",
            "dxGantt-collapseAll": "Sažmi sve",
            "dxGantt-addNewTask": "Dodaj novi zadatak",
            "dxGantt-deleteSelectedTask": "Obriši izabrani zadatak",
            "dxGantt-zoomIn": "Uvećaj",
            "dxGantt-zoomOut": "Umanji",
            "dxGantt-fullScreen": "Ceo ekran",
            "dxGantt-quarter": "Kv {0}",
            "dxGantt-sortingAscendingText": "Sortiraj rastuće",
            "dxGantt-sortingDescendingText": "Sortiraj opadajuće",
            "dxGantt-sortingClearText": "Obriši sortiranje",
            "dxGantt-showResources": "Prikaži resurse",
            "dxGantt-showDependencies": "Prikaži zavisnosti",
            "dxGantt-dialogStartDateValidation": "Početni datum mora biti nakon {0}",
            "dxGantt-dialogEndDateValidation": "Krajnji datum mora biti nakon {0}",
            "dxGallery-itemName": "Stavka galerije",
            "dxMultiView-elementAriaRoleDescription": "Višestruki prikaz",
            "dxMultiView-elementAriaLabel": "Koristite strelice ili prevucite za navigaciju između prikaza",
            "dxMultiView-itemAriaRoleDescription": "Prikaz",
            "dxMultiView-itemAriaLabel": "{0} od {1}",
            "dxSplitter-resizeHandleAriaLabel": "Razdelnik",
            "dxSplitter-resizeHandleAriaRoleDescription": "Separator",
            "dxStepper-optionalMark": "(Opcionalno)"
        }
    })
}));